// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamagotchis.Models;

#nullable disable

namespace Tamagotchi.Migrations
{
    [DbContext(typeof(TamagotchiContext))]
    [Migration("20240209000030_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tamagotchis.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Fullness")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("ShopId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Fullness = 10,
                            ItemType = "Food",
                            Name = "Kibble",
                            Quantity = 1,
                            ShopId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            Fullness = 20,
                            ItemType = "Food",
                            Name = "Canned",
                            Quantity = 1,
                            ShopId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            Fullness = 35,
                            ItemType = "Food",
                            Name = "Filet-Mignon",
                            Quantity = 1,
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("Tamagotchis.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Alive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Attention")
                        .HasColumnType("int");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<int>("Fullness")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeeding")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHatched")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSleeping")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Tamagotchis.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("Tamagotchis.Models.Toy", b =>
                {
                    b.Property<int>("ToyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Excitement")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("ToyId");

                    b.HasIndex("ShopId");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            ToyId = 1,
                            Excitement = 20,
                            ItemType = "Toy",
                            Name = "Ball",
                            Quantity = 1,
                            ShopId = 1
                        },
                        new
                        {
                            ToyId = 2,
                            Excitement = 30,
                            ItemType = "Toy",
                            Name = "Bone",
                            Quantity = 1,
                            ShopId = 1
                        },
                        new
                        {
                            ToyId = 3,
                            Excitement = 50,
                            ItemType = "Toy",
                            Name = "Frisbee",
                            Quantity = 1,
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("Tamagotchis.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Money")
                        .HasColumnType("double");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tamagotchis.Models.Food", b =>
                {
                    b.HasOne("Tamagotchis.Models.Shop", "Shop")
                        .WithMany("Foods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Tamagotchis.Models.Pet", b =>
                {
                    b.HasOne("Tamagotchis.Models.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tamagotchis.Models.Toy", b =>
                {
                    b.HasOne("Tamagotchis.Models.Shop", "Shop")
                        .WithMany("Toys")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Tamagotchis.Models.Shop", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("Toys");
                });

            modelBuilder.Entity("Tamagotchis.Models.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
